# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-04-06 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20170213_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
