# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import lmn.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0007_auto_20170418_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, upload_to='images/', validators=[lmn.validators.file_size, lmn.validators.image_extensions]),
        ),
    ]
